[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1 # Board genérico
framework = arduino

monitor_speed = 115200
board_build.filesystem = littlefs

#Características esp32-s3-devkitc-1-n16r8v
build_flags= -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

#Bibliotecas
lib_deps = 
    h2zero/NimBLE-Arduino
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    tzapu/WiFiManager